org.gradle.jvmargs=-Xmx384m -XX:+UseSerialGC -XX:MaxMetaspaceSize=384m -XX:CICompilerCount=2 -XX:TieredStopAtLevel=1 -Xss256k
kotlin.daemon.jvmargs=-Xmx256m -XX:+UseSerialGC -XX:CICompilerCount=2 -XX:TieredStopAtLevel=1 -Xss256k
kotlin.compiler.execution.strategy=in-process
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.from-registry=false
android.useAndroidX=true
