-- =============================================================================
-- V1__initial_schema.sql
-- Authoritative schema for offline distributed payment system (Phase 7)
-- Compatible with PostgreSQL 16 production and H2 (MODE=PostgreSQL) tests
-- =============================================================================

-- 1. Accounts table (Authoritative Financial Store for liquid & escrow balances)
CREATE TABLE accounts (
    vpa VARCHAR(255) PRIMARY KEY,
    holder_name VARCHAR(255) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL CHECK (balance >= 0),
    offline_locked_balance NUMERIC(19, 2) NOT NULL DEFAULT 0.00 CHECK (offline_locked_balance >= 0),
    public_key VARCHAR(128) NOT NULL,
    key_algorithm VARCHAR(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

-- 2. Offline Wallets table (Authoritative Escrow & Counter Tracking)
CREATE TABLE offline_wallets (
    wallet_id VARCHAR(64) PRIMARY KEY,
    owner_vpa VARCHAR(255) NOT NULL REFERENCES accounts(vpa),
    allocated_amount NUMERIC(19, 2) NOT NULL CHECK (allocated_amount >= 0),
    settled_amount NUMERIC(19, 2) NOT NULL DEFAULT 0.00 CHECK (settled_amount >= 0),
    remaining_amount NUMERIC(19, 2) NOT NULL CHECK (remaining_amount >= 0),
    wallet_epoch BIGINT NOT NULL,
    last_settled_counter BIGINT NOT NULL DEFAULT 0,
    valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('ACTIVE', 'EXPIRED', 'LOCKED_DISPUTED', 'AUDIT_REQUIRED', 'RECONCILED_CLOSED')),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_wallet_escrow_bounds CHECK (settled_amount + remaining_amount <= allocated_amount)
);

CREATE INDEX idx_wallets_owner ON offline_wallets(owner_vpa);
CREATE INDEX idx_wallets_status ON offline_wallets(status);

-- 3. Transactions table (Authoritative Ledger & Idempotency Barrier)
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    packet_hash VARCHAR(64) NOT NULL CONSTRAINT uk_transactions_packet_hash UNIQUE,
    sender_vpa VARCHAR(255) NOT NULL REFERENCES accounts(vpa),
    receiver_vpa VARCHAR(255) NOT NULL REFERENCES accounts(vpa),
    amount NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    signed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    settled_at TIMESTAMP WITH TIME ZONE,
    bridge_node_id VARCHAR(64) NOT NULL,
    hop_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL CHECK (status IN ('SETTLED', 'REJECTED', 'CONFLICTING', 'PENDING_SEQUENCE_GAP')),
    wallet_id VARCHAR(64) REFERENCES offline_wallets(wallet_id),
    sequence_counter BIGINT,
    conflict_reason VARCHAR(128),
    winning_transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
    receipt_signature VARCHAR(512)
);

CREATE INDEX idx_transactions_packet_hash ON transactions(packet_hash);
CREATE INDEX idx_transactions_sender ON transactions(sender_vpa);
CREATE INDEX idx_transactions_receiver ON transactions(receiver_vpa);
CREATE INDEX idx_transactions_status ON transactions(status);
CREATE INDEX idx_transactions_wallet ON transactions(wallet_id);
CREATE INDEX idx_transactions_signed_at ON transactions(signed_at);
CREATE INDEX idx_transactions_settled_at ON transactions(settled_at);
